lst = ['nol','satu', 'dua', 'tiga']
lst2 = [ kata[-2:] for kata in lst ]
a,b = 57,12
s = 'B'
print( a % b ) # cetak .............
print( b % a ) # cetak .............
print( (a < b) or (a != b) ) # cetak .............
print( ord(s) ) # cetak .............
print( -10//b ) # cetak .............
print( -10%b ) # cetak .............
print( lst2 ) # cetak .............
print( lst[1][:1] ) 