def swap1(x, y):
    x,y = y,x
    print(x,y)
def swap2(lst, index1, index2):
    lst[index1],lst[index2] = lst[index2],lst[index1]
    print(lst[index1],lst[index2])
def swap3(x, y):
    temp = x
    x = y
    y = temp
    print(x,y)
numList = [5,6,7,8,9]
swap1(numList[3], numList[4]) # cetak ……………………………………………………
print(numList) # cetak …………………………………………………………………………………
swap2(numList, 2, 3) # cetak ……………………………………………………
print(numList) # cetak …………………………………………………………………………………
swap3(numList[1], numList[2]) # cetak ……………………………………………………
print(numList) # cetak ……………………………